drop table if exists accounts CASCADE;
drop table if exists transactions CASCADE;
drop table if exists user_authorities CASCADE;
drop table if exists users CASCADE;
drop sequence if exists hibernate_sequence;

create sequence hibernate_sequence start with 1 increment by 1;

create table accounts
(
    id           bigint generated by default as identity,
    account_name varchar(255) not null,
    amount       double       not null check (amount >= 0),
    primary key (id)
);

create table transactions
(
    id               bigint generated by default as identity,
    amount           double        not null check (amount >= 0),
    date_time        timestamp     not null,
    description      varchar(5000) not null,
    transaction_type varchar(255)  not null,
    bank_account_id  bigint,
    accountant_id    binary,
    primary key (id)
);

create table user_authorities
(
    id          bigint not null,
    authority   varchar(255),
    for_user_id binary,
    primary key (id)
);

create table users
(
    id         binary       not null,
    is_enabled boolean      not null,
    full_name  varchar(255) not null,
    password   varchar(255) not null,
    username   varchar(255) not null,
    primary key (id)
);

alter table accounts
    add constraint UK_ef8srjaet88qrf7w1mvtop0pp unique (account_name);
alter table users
    add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table transactions
    add constraint FK57bkxus00yjdg642dfju9bmdc foreign key (bank_account_id) references accounts;
alter table transactions
    add constraint FK4o6tlw10qplxmuw3eg1y3niun foreign key (accountant_id) references users;
alter table user_authorities
    add constraint FKtca7w8jewwj4orarqpgtmvwri foreign key (for_user_id) references users